require 'pry-byebug'
require 'date'
require 'json'

require_relative 'lib/calculator/prices'
require_relative 'lib/calculator/periods'
require_relative 'lib/calculator/commissions'
require_relative 'lib/calculator/option_prices'
require_relative 'lib/calculator/drivy_calculator'
require_relative 'lib/printer/json_printer'
require_relative 'lib/transaction/rental_transaction'
require_relative 'lib/transaction/transaction_processor'
require_relative 'lib/transaction/commission_transaction'
require_relative 'lib/transaction/action_transaction'
require_relative 'lib/transaction/transaction_beneficiaries'
require_relative 'lib/fleet/car'
require_relative 'lib/fleet/car_fleet'
require_relative 'lib/fleet/car_options'

Transaction::TransactionProcessor.process('data/input.json', 'data/output.json')
